# This is the project specific Settings.yml file.
# Place Sphinx specific build information here.
# Settings given here will replace the settings of 'conf.py'.

---
conf.py:
  copyright: 2000-2014
  project: LDAP / SSO Authentication
  version: 1.3
  release: 1.3.1-dev
  latex_documents:
  - - Index
    - ig_ldap_sso_auth.tex
    - LDAP / SSO Authentication
    - Xavier Perseguers \and Team Infoglobe
    - manual
  latex_elements:
    papersize: a4paper
    pointsize: 10pt
    preamble: \usepackage{typo3}
  latex_show_pagerefs: True
  extensions:
    - sphinx.ext.intersphinx
    - sphinx.ext.extlinks
  extlinks:
    forge:
    - https://forge.typo3.org/issues/%s
    - 'Forge ticket #'
    ter:
    - http://www.typo3.org/extensions/repository/view/%s
    - 'EXT:'
...
